- hosts: all
  become: yes
  tasks:
    - name: Installeer Apache2 via shell
      shell: apt-get update && apt-get install -y apache2
      args:
        warn: false
      register: apache_install
      changed_when: "'0 upgraded, 0 newly installed' not in apache_install.stdout"

    - name: Laat bewust een fout zien
      command: /bin/false
