---
name: Terraform
on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:
jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Format Check
        run: terraform -chdir=terraform fmt -check
      - name: Terraform Validate
        run: terraform -chdir=terraform validate
  apply:
    needs: validate
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
  destroy:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
